# Generated by Django 4.2.7 on 2025-11-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="querylog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Query Log",
                "verbose_name_plural": "Query Logs",
            },
        ),
        migrations.AddField(
            model_name="querylog",
            name="avg_similarity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="querylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="querylog",
            name="processing_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="querylog",
            name="source_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="querylog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
